# docker/docker-compose.yml
version: '3.8'

services:
  database:
    image: mariadb:latest
    networks:
      - app-tier
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./database/data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    networks:
      - app-tier
    depends_on:
      - database
    ports:
      - 8088:80
    environment:
      PMA_HOST: database

  php-fpm:
    image: kyllians/php-fpm-symfony:8.2.0RC2-fpm-buster
    environment:
      - 'PS1=\033[01;32m\]\u@docker_\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
    networks:
      - app-tier
    volumes:
      - ./php-fpm/configs:/cfgs
      - ../src:/var/www
    depends_on:
      - database
    env_file: .env

  nginx:
    build:
      context: nginx
    networks:
      - app-tier
    volumes:
      - ../src:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
      - ./nginx/cert:/etc/ssl/
    depends_on:
      - php-fpm
    links:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"

  node:
    image: "node:latest"
    working_dir: /var/www/nuitISEN
    networks:
      - app-tier
    environment:
      - NODE_ENV=dev
    command:
      - /bin/sh
      - -c
      - |
        yarn install
        yarn encore dev-server
    volumes:
      - ../src:/var/www
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - php-fpm
    links:
      - php-fpm

networks:
  app-tier:
    driver: bridge